-- Complete VMLBrain Schema for Neon
-- Generated for Supabase → Neon migration

-- ============================================
-- 1. Enable Extensions
-- ============================================
CREATE EXTENSION IF NOT EXISTS vector;

-- ============================================
-- 2. Create Tables
-- ============================================

-- Sections table (for homepage organization)
CREATE TABLE IF NOT EXISTS sections (
  key TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  icon TEXT NULL,
  image_name TEXT NULL,
  sort_order INTEGER DEFAULT 0
);

-- Policies table (main knowledge base articles)
-- Note: Using UUID to match Supabase schema
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS policies (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  slug TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  summary TEXT,
  body_md TEXT,
  parent_slug TEXT,
  section_key TEXT NULL REFERENCES sections(key),
  box_folder_id TEXT NULL,
  box_file_ids TEXT[] NULL,
  audience TEXT[] DEFAULT ARRAY['All'],
  status TEXT DEFAULT 'approved',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  FOREIGN KEY (parent_slug) REFERENCES policies(slug) ON DELETE SET NULL
);

-- Profiles table (people directory)
CREATE TABLE IF NOT EXISTS profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  job_title TEXT NOT NULL,
  description_html TEXT NOT NULL,
  clients TEXT[] DEFAULT '{}'::TEXT[],
  experience TEXT,
  photo_url TEXT,
  email TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'approved' CHECK (status IN ('approved','draft')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Policy embeddings table (for AI chatbot)
CREATE TABLE IF NOT EXISTS policy_embeddings (
  id BIGSERIAL PRIMARY KEY,
  policy_id UUID REFERENCES policies(id) ON DELETE CASCADE,
  policy_slug TEXT NOT NULL,
  chunk_index INT NOT NULL,
  content TEXT NOT NULL,
  embedding vector(1536), -- OpenAI ada-002 embedding size
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(policy_slug, chunk_index)
);

-- Profile embeddings table (for AI chatbot)
CREATE TABLE IF NOT EXISTS profile_embeddings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id BIGINT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  profile_slug TEXT NOT NULL,
  chunk_index INT NOT NULL,
  content TEXT NOT NULL,
  embedding vector(1536) NOT NULL
);

-- ============================================
-- 3. Create Indexes
-- ============================================

-- Policy embeddings indexes
CREATE INDEX IF NOT EXISTS policy_embeddings_embedding_idx
  ON policy_embeddings
  USING ivfflat (embedding vector_cosine_ops)
  WITH (lists = 100);

CREATE INDEX IF NOT EXISTS policy_embeddings_policy_slug_idx
  ON policy_embeddings(policy_slug);

-- Profile embeddings indexes
CREATE INDEX IF NOT EXISTS profile_embeddings_slug_idx
  ON profile_embeddings (profile_slug);

-- ============================================
-- 4. RLS Policies (Disabled for Neon)
-- ============================================
-- Note: RLS is a Supabase feature. For Neon, we use application-level
-- access control since all queries go through the application server.
--
-- If you want to enable RLS in Neon, uncomment these lines:
--
-- ALTER TABLE policies ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE policy_embeddings ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE profile_embeddings ENABLE ROW LEVEL SECURITY;
--
-- CREATE POLICY "Allow public read access"
--   ON policies FOR SELECT TO PUBLIC
--   USING (status = 'approved');
--
-- (etc...)

-- ============================================
-- 6. Create Functions
-- ============================================

-- Function to search policy embeddings
CREATE OR REPLACE FUNCTION match_policy_embeddings(
  query_embedding vector(1536),
  match_threshold float DEFAULT 0.7,
  match_count int DEFAULT 5
)
RETURNS TABLE (
  id bigint,
  policy_slug text,
  chunk_index int,
  content text,
  similarity float
)
LANGUAGE sql STABLE
AS $$
  SELECT
    policy_embeddings.id,
    policy_embeddings.policy_slug,
    policy_embeddings.chunk_index,
    policy_embeddings.content,
    1 - (policy_embeddings.embedding <=> query_embedding) as similarity
  FROM policy_embeddings
  WHERE 1 - (policy_embeddings.embedding <=> query_embedding) > match_threshold
  ORDER BY policy_embeddings.embedding <=> query_embedding
  LIMIT match_count;
$$;

-- Function to search profile embeddings
CREATE OR REPLACE FUNCTION match_profile_embeddings (
  query_embedding vector(1536),
  match_threshold float,
  match_count int
) RETURNS TABLE (
  id bigint,
  profile_slug text,
  content text,
  chunk_index int,
  similarity float
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    pe.id,
    pe.profile_slug,
    pe.content,
    pe.chunk_index,
    1 - (pe.embedding <-> query_embedding) as similarity
  FROM profile_embeddings pe
  WHERE 1 - (pe.embedding <-> query_embedding) >= match_threshold
  ORDER BY pe.embedding <-> query_embedding
  LIMIT match_count;
END;
$$;

-- ============================================
-- 7. Create Views (optional helpers)
-- ============================================

CREATE OR REPLACE VIEW profile_meta AS
SELECT
  slug,
  (first_name || ' ' || last_name) as full_name,
  job_title
FROM profiles;

-- ============================================
-- Schema creation complete!
-- Next: Import data using data export script
-- ============================================
